# Support this open-source project.
# Maintained by Waren Gonzaga under WG Technology Labs with contributions from the community.
# GitHub Sponsors: https://github.com/sponsors/wgtechlabs
# Buy Me a Coffee: https://buymeacoffee.com/wgtechlabs

github: wgtechlabs
buy_me_a_coffee: wgtechlabs

# Your support directly funds continued development, maintenance, and new features.
# Every contribution helps ensure this project remains free, up-to-date, and accessible to all.